#:schema node_modules/wrangler/config-schema.json
name = "github-notification-notifier"
main = "src/index.ts"
compatibility_date = "2024-07-12"
workers_dev = false

[triggers]
crons = ["*/5 * * * *"]

[[kv_namespaces]]
binding = "kv"
id = "7925cc7dd9ba4530a51585b6d410d2ce"
